[ssh]
Host = "localhost"
Port = 22222
PublicUrl = "http://localhost:22222"
KeyPath = ".ssh/id_ed25519"

[container]
ContainerPort = 1337
TimeoutInMinutes = 30

[challenge]
BaseDir = "challenges/2024"
